@@startuml
skinparam nodesep 100
skinparam ranksep 100

actor person1
actor person2
actor person3

[Validator\nDNB] as dnb
[Validator\nNordea] as nordea
[Validator\nSparebank1] as sparebank1
[Validator\nEika] as eika
[Validator\nBN bank] as bnbank

person1-down->dnb
person2-down->nordea:\n bank customers staking deposits\nwith consumer banks
person3-down->eika

rectangle "Norway blockchain" as norwaychain #FF4444 {
    [<b>NOK Fungible Token contract</b>\nVAT on purchases\nIncome tax] as ft
    [<b>SEK Fungible Token contract</b>] as ftsekno
    [<b>Employment contract</b>] as employeecontract
    [<b>Insurance contract</b>] as insurance
    [<b>Voting contract</b>] as voting
    [<b>Asset ownership contract</b>\nNon Fungible Tokens] as nft
    employeecontract-[hidden]down-ft
    insurance-[hidden]down-voting
    ftsekno-[hidden]down-nft
}

[<b>Central bank of Norway</b>\n- Governance\n- Protocol upgrades\n- RPC gateway] as norgesbank #FFFFFF

package "Central bank of Sweden" as swedenbank #FFFF55 {
    [<b>SEK Fungible Token contract</b>] as ftse
    [<b>NOK Fungible Token contract</b>] as ftnokse
    ftnokse-[hidden]right-ftse
}
ftnokse-left-ft : bridge
ftse-left-ftsekno : bridge

cloud "Other decentralized blockchains" #DDDDDD {
    package "Ethereum" as eth {
        [NOK Fungible token] as ftnoketh
    }
    package "NEAR protocol" as near {
        [NOK Fungible token] as ftnoknear
    }

    [Solana]
    [Bitcoin]
}
ftnoketh-up-ft : bridge
ftnoknear-up-ft : bridge

dnb-down->norwaychain
nordea-down->norwaychain
sparebank1-down->norwaychain
eika-down->norwaychain
bnbank-down->norwaychain

norgesbank-up->ft

@@enduml